// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/21/2025, 5:50:42 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/USER/Desktop/projects/negestat/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/negestat/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/negestat/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/negestat/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/negestat/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/negestat/plugins/**/*.{js,ts,mjs}","C:/Users/USER/Desktop/projects/negestat/composables/**/*.{js,ts,mjs}","C:/Users/USER/Desktop/projects/negestat/utils/**/*.{js,ts,mjs}","C:/Users/USER/Desktop/projects/negestat/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/negestat/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/negestat/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;